version: "3.3"

services:

  app:
    image: donutdrifter/app
    restart: always
    ports:
      - 3010:3000
    environment:
      REACT_APP_PATH: 'http://localhost:5010/api/Integral'

  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - 9000:9000

  integral:
    image: donutdrifter/integralservice
    restart: always
    ports:
      - 5010:5000