version: "3.9"
services:
  app:
    build:
      context: .
    volumes:
      - .:/react-integral
    ports:
      - 3000:3000
    image: donutdrifter/app:react-integral
    container_name: react_container
    command: npm start