// export const CHANGEA= 'CHANGEA'
// export const CHANGEB= 'CHANGEB'
// export const CHANGEN= 'CHANGEN'
// export const CHANGEIE= 'CHANGEIE'
export const CALC= 'Calculate'
export const DELALL= 'DeleteAll'
export const DEL= 'Delete'